config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :articles, shallow: true do
   resources :likes
    resources :comments, shallow: true do
      resources :likes
    end
  end
  root 'articles#home'
end	     

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_many :likes, as: :likeable

	def self.most_recent(limit)
   order("created_at desc").limit(limit)
  end
  
end
# has_many :pictures, as: :imageable

app/models/comment.rb
class Comment < ApplicationRecord
  # has_many :likes, dependent: :destroy
  belongs_to :article
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy 
  # validates_uniqueness_of :user_id, scope: [:comment_id]
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	def after_sign_in_path_for(resource)
    articles_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

	def index
    @articles = Article.all
    respond_to do |format|
      format.html
      format.js { render json: @articles }
    end
  end

  def new
    @article = Article.new
  end
   
  def show
  end
  
	def create
		@article = Article.new(article_param)
		if @article.save
		  redirect_to article_path(@article)
		else
		  render :new
		end
	end
  
  def edit
  end

  def update
	  if @article.update_attributes(article_param)
	    redirect_to article_path(@article)
	  else
	    render :edit
	  end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end 

  def home
  end  
   
  private

  def article_param
    params.require(:article).permit(:name,:description)
  end

  def find_article
    @article = Article.find(params[:id])
  end  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @article = @comment.article_id 
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :comment)
    end
end

app/controllers/likes_controller.rb
  
class LikesController < ApplicationController
  before_action :find_likeable, only: [:create]
  
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @likable.likes.create(user_id: current_user.id)
    end
    # redirect_to root_path
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
  end

  def self.already_liked?
    Like.where(user_id: current_user.id, likeable_id: params[:likeable_id]).exists?
  end

  private

  def find_likeable
  	@likable = params[:likeable_type].constantize.find(params[:likeable_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<div class="container">
  <div class="card shadow-sm p-3">
    <div class="card-body">
      <%= form_with model: @article, local: true do |form| %>
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@article.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
       
        <div class="form-group">
          <%= form.label :name, for: "name" %><br>
          <%= form.text_field :name, class: "form-control" %>
        </div>
       
        <div class="form-group">
          <%= form.label :description, for: "description" %><br>
          <%= form.text_area :description, class: "form-control" %>
        </div>
       
        <div class="form-group">
          <%= form.submit "Submit", class: 'btn btn-primary ml-1' %>
          &nbsp; <%= link_to 'Back', articles_path, class: "btn btn-info" %>
        </div>
      <% end %>
    </div>  
  </div>
</div>
    

app/views/articles/edit.html.erb
<h1 class='head'>Edit article</h1>
 
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<a href='javascript:void(0)' id='all-articles' onclick="callExecuter()" class='btn btn-default'>show all articles</a>   
<div id="somedemo"></div>

 <h1 class="head1">Listing Articles</h1>
    <p class="btn">
      <%= link_to 'New article', new_article_path, class: "btn btn-primary" %>
    </p>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <tr>
          <th>Author Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
 
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.name %></td>
            <td><%= article.description %></td>

            <td>
              <%= link_to 'Show', article_path(article), class: "btn btn-success"%>
            </td>
            <td>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-default"%>
            </td>
            <td>
              <%= link_to 'Destroy', article_path(article), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
       <% end %>
      </table>
    </div>



<script>
var callExecuter=function(){
  // debugger
  $.ajax({
    type:'GET',
    dataType: 'json',
    url:'<%= articles_path %>',
    success:function(response){
      //I assume you want to do something on controller action execution success?
      // response.forEach(function(article){$('#somedemo').append(article.name," ", article.description);
      response.forEach(function(article){ $article_html = $("<div class='article'>" + article.name + "</div>"); $('#somedemo').append($article_html); });
    }
  });
}

// $(document).on("click","#all-articles",callExecuter);
</script>

<!-- 
data.users.forEach(function(user){ $user_html = $("<div class='user'>" + user.name + "</div>"); $('#usersList').append($user_html); });

response.forEach(function(user){ $article_html = $("<div class='article'>" + article.name + "</div>"); $('#somedemo').append($article_html); }); -->

app/views/articles/new.html.erb
<h1 class='head'>New article</h1>
 
<%= render 'articles/form' %>

app/views/articles/show.html.erb
<a href='javascript:void(0)' id='all-articles' onclick="callExecuter()" class='btn btn-default'>show all articles</a> 	
<div id="somedemo"></div>
<div class="container">
	<div class="card shadow-sm p-3">
		<div class="card-body">
			  <p>
				  <strong>Name:</strong>
				  <%= @article.name %>
				</p>
				 
				<p>
				  <strong>Description:</strong>
				  <%= @article.description %>
				</p>
	
				<p>
					<%= link_to 'Like Article', article_likes_path(@article, likeable_type: @article.class, likeable_id: @article.id), class: "btn btn-primary", method: :post, remote: true, id: 'like-btn'%>
				</p>	
        
        <p>                                 
	        <% @article.likes.each do |like| %>
					  <% if like.user_id == current_user.id %>
					    <%= link_to 'Unlike', like_path(like), class: "btn btn-primary", method: :delete, remote: true, id: 'unlike-btn'%>
					  <% end %>
					<% end %>
			  </p>
				                                        
        <p>
					<% if (@article.likes.count) == 1 %>
						<p><%= @article.likes.count %> Like</p>
					<% elsif (@article.likes.count) > 1 %>
				    <p><%= @article.likes.count %> Likes</p>
					<% else %>
						<%= 'not liked yet by any one' %>		 
					<% end %>	
        </p>

				<h2>Comments</h2>
				<%= render @article.comments %>

				<h4>Add a comment:</h4>
				<% if current_user %>
					<%= render 'comments/form' %>
				<% else %>
				<p> You must sign in to comment. </p>
				<% end %>				
		</div>
	</div>
</div>

<!-- <a id="all-articles" href="">show all articles</a>


<script>
	$(document).ready(function() {
	 	$('#all-articles').on('click', function(){
	 		console.log("r5r5t");
	 		debugger
	 		$.get("/articles", function(data) {
		  	$('#demo').html(data);
			});
	 	});
	});
</script> -->




<script>
var callExecuter=function(){
  // debugger
  $.ajax({
    type:'GET',
    dataType: 'json',
    url:'<%= articles_path %>',
    success:function(response){
      //I assume you want to do something on controller action execution success?
      response.forEach(function(article){
        $('#somedemo').append(article.name);
    	});
    }
  });
}

// $(document).on("click","#all-articles",callExecuter);
</script>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.user.email %>
</p>
 
<p>
    <strong>Comment:</strong>
    <%= comment.comment %>
</p>

<p>
  <%= link_to 'Like Comment', comment_likes_path(comment, likeable_type: comment.class, likeable_id: comment.id), class: "btn btn-info", method: :post, remote: true, id: "like-btn" %>
</p>

<p>                                 
  <% comment.likes.each do |like| %>
	  <% if like.user_id == current_user.id %>
	    <%= link_to 'unlike', like_path(like), class: "btn btn-primary", method: :delete, remote: true, id: 'ulike-btn'%>
	  <% end %>
	<% end %>
</p>

<p>
	<% if (comment.likes.count) == 1 %>
		<p><%= comment.likes.count %> Like</p>
	<% elsif (comment.likes.count) > 1 %>
    <p><%= comment.likes.count %> Likes</p>
	<% else %>
		<%= 'not liked yet by any one' %>		 
	<% end %>	
</p>

<p>
  <%= link_to 'Destroy Comment', comment_path(comment), class: "btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
      <%= form.label :comment, for: "comment" %><br>
      <%= form.text_area :comment, class: "form-control" %>
    </div> 
  <div class="form-group">
    <%= form.submit "Create comment" , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <%= current_user.email %>        
      </li>
    <% else %>
      <li>
      <%= link_to('Login', new_user_session_path) %>  
      </li>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<%= form_with model: @article, local: true do |form| %>
  
<% end %>